### ISSUE TITLE
Easter eggs with .8ball

### ISSUE THREAD

**Issue by tomodachi94** [SizableShrimp/JSB#4]
Hi,
Astro wanted there to be a certain response upon entering a certain phrase, such as:
`Will Xbony2 become an editor?`

❤️ 
EDIT: Astro is unpleased I made an issue about this.

**Comment by SizableShrimp** [comment]
I'm not adding this. It's very minimal, and I want it to work the same as the command from santa's bot. Hardcoding messages is boring.
